#!/usr/bin/env python3
"""Generate THIRD-PARTY-LICENSES.md from the dependency graph.

Why this exists: nearly every dependency is MIT or Apache-2.0, and both require
that their copyright notice and license text travel with any distribution of a
binary that includes them. Publishing a tarball or a Docker image without this
file is a license violation, however permissive the licenses are.

Only what is actually shipped is listed: dev-dependencies are excluded (they
never enter the binary) and the graph is resolved for one target platform, so
crates for other operating systems do not inflate the file.

Reads license texts from the local cargo registry, so it needs no network and no
extra tooling. Texts are deduplicated by content: two crates under an identical
MIT text share one entry, while a crate whose notice differs keeps its own.
"""
import hashlib
import json
import subprocess
import sys
from pathlib import Path

TARGET = "x86_64-unknown-linux-gnu"
LICENSE_FILENAMES = ("LICENSE", "LICENSE.md", "LICENSE.txt", "LICENSE-MIT",
                     "LICENSE-APACHE", "LICENCE", "COPYING", "UNLICENSE",
                     "LICENSE-MIT.md", "LICENSE-APACHE.md")


def shipped_packages():
    """Packages reachable from the root through normal/build deps only."""
    meta = json.loads(subprocess.run(
        ["cargo", "metadata", "--format-version", "1", "--filter-platform", TARGET],
        capture_output=True, text=True, check=True).stdout)
    by_id = {p["id"]: p for p in meta["packages"]}
    nodes = {n["id"]: n for n in meta["resolve"]["nodes"]}
    root = meta["resolve"]["root"]

    seen, stack = set(), [root]
    while stack:
        current = stack.pop()
        if current in seen:
            continue
        seen.add(current)
        for dep in nodes.get(current, {}).get("deps", []):
            kinds = {k.get("kind") for k in dep.get("dep_kinds", [])}
            # kind None == a normal dependency; "dev" never ships.
            if kinds and kinds <= {"dev"}:
                continue
            stack.append(dep["pkg"])
    seen.discard(root)
    return sorted((by_id[i] for i in seen), key=lambda p: (p["name"], p["version"]))


def license_texts(package):
    """Every license file shipped inside the crate, as (filename, text)."""
    manifest = Path(package["manifest_path"]).parent
    found = []
    for name in LICENSE_FILENAMES:
        path = manifest / name
        if path.is_file():
            try:
                found.append((name, path.read_text(encoding="utf-8", errors="replace").strip()))
            except OSError:
                pass
    return found


def main():
    packages = shipped_packages()
    texts, missing = {}, []
    for package in packages:
        entries = license_texts(package)
        if not entries:
            missing.append(package)
            continue
        for name, text in entries:
            digest = hashlib.sha256(text.encode()).hexdigest()
            texts.setdefault(digest, {"text": text, "file": name, "crates": []})
            texts[digest]["crates"].append(f"{package['name']} {package['version']}")

    out = [
        "# Third-party licenses",
        "",
        "`wamux` is MIT OR Apache-2.0. It links the crates below, whose licenses",
        "require their notices to accompany any distribution of a binary built",
        f"from this source. Generated by `scripts/gen-third-party.py` for `{TARGET}`;",
        "dev-dependencies are excluded because they never reach the binary.",
        "",
        f"**{len(packages)} crates**, {len(texts)} distinct license texts.",
        "",
        "## Crates",
        "",
        "| crate | version | license |",
        "| --- | --- | --- |",
    ]
    for package in packages:
        out.append(f"| {package['name']} | {package['version']} | {package.get('license') or '(see file)'} |")

    out += ["", "## License texts", ""]
    for entry in sorted(texts.values(), key=lambda e: -len(e["crates"])):
        out.append(f"### {entry['file']} — {len(entry['crates'])} crate(s)")
        out.append("")
        out.append("<details><summary>" + ", ".join(entry["crates"][:6])
                   + (", …" if len(entry["crates"]) > 6 else "") + "</summary>")
        out.append("")
        out.append("```")
        out.append(entry["text"])
        out.append("```")
        out.append("")
        out.append("</details>")
        out.append("")

    if missing:
        out += ["## Crates with no license file in the published package", "",
                "Their SPDX identifier above is the authoritative statement:", ""]
        out += [f"- {p['name']} {p['version']} — {p.get('license') or 'NO LICENSE FIELD'}" for p in missing]
        out.append("")

    Path("THIRD-PARTY-LICENSES.md").write_text("\n".join(out))
    print(f"THIRD-PARTY-LICENSES.md: {len(packages)} crates, {len(texts)} textos, {len(missing)} sem arquivo")
    for package in missing:
        if not package.get("license"):
            print(f"  !! {package['name']} {package['version']}: sem campo license E sem arquivo", file=sys.stderr)


if __name__ == "__main__":
    main()
